/* FILTRANDO OS VALORES NULL */
SELECT NOME, SEXO, ENDERECO
FROM CLIENTE
WHERE SEXO = 'F';

SELECT NOME, SEXO, ENDERECO 
FROM CLIENTE
WHERE EMAIL IS NULL;

SELECT NOME, SEXO, ENDERECO 
FROM CLIENTE
WHERE EMAIL IS NOT NULL;

/* IS NULL OU NOT NULL */

/* UTILIZANDO O UPDATE PARA ATUALIZAR VALORES */
SELECT NOME, EMAIL
FROM CLIENTE;

UPDATE CLIENTE
SET EMAIL = 'KAMIJI@EMAIL.COM';

/* WHERE - VAI SER O SEU MELHOR AMIGO DA VIDA PRA VIDA INTEIRA */
SELECT * FROM CLIENTE
WHERE NOME = 'DIAS';

UPDATE CLIENTE
SET EMAIL = 'DIAS@EMAIL.COM'
WHERE NOME = 'DIAS';

UPDATE CLIENTE
SET EMAIL = 'LULU@EMAIL.COM'
WHERE NOME = 'LULU';

UPDATE CLIENTE
SET EMAIL = 'JOAO@EMAIL.COM'
WHERE NOME = 'JOAO';

UPDATE CLIENTE
SET EMAIL = 'ANA@MAIL.COM'
WHERE NOME = 'ANA';

UPDATE CLIENTE
SET EMAIL = 'DONA@GMAIL.COM'
WHERE NOME = 'DONA';

/* COMIT E ROLLBACK*/

/* DELETANDO REGISTROS COM A CLAUSULA DELETE */
-- TOTAL 5
SELECT * FROM CLIENTE
WHERE NOME = 'ANA';

DELETE FROM CLIENTE; /* DELETA TODAS AS LINHAS*/

DELETE FROM CLIENTE /* USAR O DELETE SEMPRE COM O WHERE */
WHERE NOME = 'ANA';

SELECT COUNT(*) FROM CLIENTE;
WHERE NOME = 'ANA';

DELETE FROM CLIENTE
WHERE NOME = 'ANA';

SELECT COUNT(*) FROM CLIENTE; 

SELECT 5 - 1;

INSERT INTO CLIENTE VALUES ('CARLA', 'F', 'CLOPES@UOL.COM', '123456789', '33459042', 'RUA COPPER LEAF - WILLIANSBURG - KITCHER' );
INSERT INTO CLIENTE VALUES ('CARLA', 'F', 'CARLINHA@UOL.COM', '123456789', '33459042', 'RUA COPPER LEAF - WILLIANSBURG - KITCHER' );

DELETE FROM CLIENTE
WHERE NOME = 'CARLA'
OR 'EMAIL' = 'CARLINHA@UOL.COM';

SELECT * FROM CLIENTE -- OR TRAS TODO MUNDO COM APENAS UMA DAS DUAS CONDICOÇÕES
WHERE NOME = 'CARLA'
OR 'EMAIL' = 'CARLINHA@UOL.COM';

SELECT * FROM CLIENTE -- TRAS APENAS O REGISTRO QUE SATISFAÇA AS DUAS CONFIÇÕES
WHERE NOME = 'CARLA'
AND 'EMAIL' = 'CLOPES@UOL.COM';

DELETE FROM CLIENTE
WHERE NOME = 'CARLA'
AND 'EMAIL' = 'CLOPES@UOL.COM';

SELECT * FROM CLIENTE;

/* ENTRANDO COM MAIS TELEFONES */

UPDATE CLIENTE
SET TELEFONE = '997797018'
WHERE NOME = 'DIAS';

SELECT * FROM CLIENTE;

SELECT SEXO, COUNT(*) FROM CLIENTE
GROUP BY SEXO;

SELECT ENDERECO, COUNT(*) FROM CLIENTE
GROUP BY ENDERECO;