/* Modelagem básica */

CLIENTE 

NOME - CARACTER (30)
CPF - NUMÉRICO(11)
EMAIL - CARACTER(30)
TELEFONE - CARACTER(30)
ENDERECO - CARACTER(100)
SEXO - CARACTER(1)

/* PROCESSOS DE MODELAGEM */
 
/* FASE 01 E FASE 02 - AD = ADM DE DADOS */
MODELAGEM CONCEITUAL - RASCUNHO
MODELAGEM LÓGICA - QUALQUER PROGRAMA DE MODELAGEM 

/* FASE 03 - DBA / AD */

MODELAGEM FÍSICA - SCRIPTS DE BANCO 

/* INICIANDO A MODELAGEM FÍSICA */

/* CRIANDO O BANCO DE DADOS */

CREATE DATABASE PROJETO;

/* CONECTANDO-SE AO BANCO */

USE PROJETO;

/* CRIANDO A TABELA DE CLIENTES */

CREATE TABLE CLIENTE(
    NOME VARCHAR(30),
    SEXO CHAR(1),
    EMAIL VARCHAR(30),
    CPF VARCHAR(30),
    TELEFONE VARCHAR(30),
    ENDERECO VARCHAR(100)
);

/* VERIFICANDO AS TABELAS DO BANCO */

SHOW TABLES;

/* DESCOBRINDO COMO É A ESTRUTURA DE UMA TABELA */

DESC CLIENTE;

/* SINTAXE BASICA DE INSERÇÃO -- INSERT INTO TABELA */

/* FORMA 01 - OMITINDO AS COLUNAS */
INSERT INTO CLIENTE VALUES ('DIAS', 'M', 'DIAS@GMAIL.COM', '123456789', '33459042', 'PENHA - SC');
INSERT INTO CLIENTE VALUES ('LULU', 'F', 'LULU@GMAIL.COM', '123456789', '33459042', 'PENHA - SC');

/* FORMA 02 - COLOCANDO AS COLUNAS */
INSERT INTO CLIENTE (NOME, SEXO, ENDERECO, TELEFONE, CPF) VALUES ('JOAO', 'M', 'PENHA - SC', '33459042', 123456789);

/* FORMA 03 - INSERT COMPACTO - SOMENTE MYSQL */

INSERT INTO CLIENTE VALUES ('ANA', 'F', 'ANA@GMAIL.COM', '123456789', '33459042', 'BRASILIA - DF'),
                           ('DONA', 'F', 'FLORINDA@GMAIL.COM', '123456789', '33459042', 'BRASILIA - DF');

/* O OCOMANDO SELECT 
    SELEÇÃO/ PROJEÇÃO E JUNÇÃO
*/

SELECT NOW () AS DATA_HORA, 'ANDREW KAMIJI' AS PROGRAMADOR;

SELECT NOW();

SELECT 'FELIPE MAFRA';

SELECT 'BANCO DE DADOS';

/* ALIAS DE COLUNAS */

SELECT NOME AS CLIENTE, SEXO, EMAIL FROM CLIENTE;

SELECT NOME, SEXO, EMAIL, ENDERECO FROM CLIENTE;

SELECT EMAIL, SEXO, ENDERECO, NOME FROM CLIENTE;

SELECT EMAIL, SEXO, ENDERECO, NOME, NOW() CLIENTE;

/* APENAS PARA FINS ACADEMICOS */

SELECT * FROM CLIENTE;

/* FILTRANDO DADOS COM WHERE E LIKE */

SELECT NOME, TELEFONE FROM CLIENTE;

/* FILTRANDO */

SELECT NOME, SEXO FROM CLIENTE
WHERE SEXO = 'M';

SELECT NOME, SEXO FROM CLIENTE
WHERE SEXO = 'F';

SELECT NOME, SEXO FROM CLIENTE
WHERE ENDERECO = 'SC';

/* UTILIZANDO O LIKE*/

SELECT NOME, SEXO FROM CLIENTE
WHERE ENDERECO LIKE 'PENHA';

/* CARACTER CORINGA % -> QUALQUER COISA */

SELECT NOME, SEXO FROM CLIENTE
WHERE ENDERECO LIKE '%SC';

SELECT NOME, SEXO, ENDERECO FROM CLIENTE
WHERE ENDERECO LIKE '%SC';

SELECT NOME, SEXO, ENDERECO FROM CLIENTE
WHERE ENDERECO LIKE 'PENHA%';