CREATE TABLE CURSOS(
    IDCURSO INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(30),
    HORAS INT,
    VALOR FLOAT(10,2),
    ID_PREREQ INT
);

ALTER TABLE CURSOS 
ADD CONSTRAINT FK_PREREQ
FOREIGN KEY(ID_PREREQ)
REFERENCES CURSOS(IDCURSO);

INSERT INTO CURSOS VALUES(NULL, 'BD RELACIONAL', 20, 400.00, NULL);
INSERT INTO CURSOS VALUES(NULL, 'BUSINESS INTELLIGENCE', 40, 800.00, 1);
INSERT INTO CURSOS VALUES(NULL, 'RELATORIOS AVANCADOS', 20, 600.00, 2);
INSERT INTO CURSOS VALUES(NULL, 'LOGICA PROGRAMACAO', 20, 400.00, NULL);
INSERT INTO CURSOS VALUES(NULL, 'RUBY', 30, 500.00, 4);

SELECT * FROM CURSOS;

SELECT NOME, VALOR, HORAS, IFNULL(ID_PREREQ, 'SEM REQ') REQUISITO
FROM CURSOS;

/* NOME, VALOR, HORAS E O NOME DO PRE REQUISITO DO CURSO */

SELECT C.NOME AS CURSO, 
       C.VALOR AS VALOR, 
       C.HORAS AS CARGA, 
       IFNULL(P.NOME, '---') AS PREREQ
FROM CURSOS C
    LEFT JOIN CURSOS P
    ON P.IDCURSO = C.ID_PREREQ;

/* CURSORES */

CREATE DATABASE CURSORES;
USE CURSORES;

CREATE TABLE VENDEDORES(
    IDVENDEDOR INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(50),
    JAN INT,
    FEV INT,
    MAR INT
);

INSERT INTO VENDEDORES VALUES(NULL, 'KAMIJI', 33245, 6548, 54466);
INSERT INTO VENDEDORES VALUES(NULL, 'ANDREW', 56456, 1203, 32145);
INSERT INTO VENDEDORES VALUES(NULL, 'ADRIAN', 23154, 5645, 6587);
INSERT INTO VENDEDORES VALUES(NULL, 'ANDREY', 5645, 9879, 65544);
INSERT INTO VENDEDORES VALUES(NULL, 'MARCELO', 6548, 4687, 3214);
INSERT INTO VENDEDORES VALUES(NULL, 'LUCIANA', 56423, 6543, 65654);

SELECT * FROM VENDEDORES;

SELECT NOME, (JAN + FEV + MAR) AS TOTAL FROM VENDEDORES;
SELECT NOME, (JAN + FEV + MAR) AS TOTAL, ( JAN + FEV + MAR)/3 AS MEDIA FROM VENDEDORES;

CREATE TABLE VEND_TOTAL(
    NOME VARCHAR(50),
    JAN INT,
    FEV INT,
    MAR INT,
    TOTAL INT,
    MEDIA INT
);

DELIMITER #

CREATE PROCEDURE INSEREDADOS()
BEGIN 
    DECLARE FIM INT DEFAULT 0;
    DECLARE VAR1, VAR2, VAR3, VTOTAL, VMEDIA INT;
    DECLARE VNOME VARCHAR(50);
    DECLARE REG CURSOR FOR(
        SELECT NOME, JAN, FEV, MAR FROM VENDEDORES
    );
    DECLARE CONTINUE HANDLER FOR NOT FOUND SET FIM = 1;
    OPEN REG;
    REPEAT 
        FETCH REG INTO VNOME, VAR1, VAR2, VAR3;
        IF NOT FIM THEN
            SET VTOTAL = VAR1 + VAR2 + VAR3;
            SET VMEDIA = VTOTAL / 3;
            INSERT INTO VEND_TOTAL VALUES(VNOME, VAR1, VAR2, VAR3, VTOTAL, VMEDIA);
        END IF;
    UNTIL FIM END REPEAT;
    CLOSE REG;
END
#

DELIMITER ;

SELECT * FROM VENDEDORES;
SELECT * FROM VEND_TOTAL;

CALL INSEREDADOS();

DROP PROCEDURE INSEREDADOS;

