/* DELIMITADOR - DELIMITER */
; -> MYSQL

SELECT C.NOME,
       C.SEXO,
       IFNULL(C.EMAIL, 'CLIENTE SEM EMAIL') AS 'EMAIL',
       T.TIPO,
       T.NUMERO,
       E.BAIRRO,
       E.CIDADE,
       E.ESTADO
FROM CLIENTE C
    INNER JOIN TELEFONE T
    ON C.IDCLIENTE = T.ID_CLIENTE
    INNER JOIN ENDERECO E
    ON C.IDCLIENTE = E.ID_CLIENTE
ORDER BY 1;

STATUS

DELIMITER $

SELECT * FROM V_RELATORIO;

DELIMITER ;

/* STORED PROCEDURES  */

SELECT 'MAFRA';

DELIMITER $

CREATE PROCEDURE NOME()
BEGIN  
    QUALQUER PROGRAMAÇÃO;
END
$

CREATE PROCEDURE NOME_EMPRESA()
BEGIN 
    SELECT 'UNIVERSIDADE DOS DADOS' AS EMPRESA;
END
$

/* CHAMANDO UMA PROCEDURE */

DELIMITER ;

CALL NOME_EMPRESA();

/* PROCEDURE COM PARAMETROS */

SELECT 10 + 10 AS CONTA;

DELIMITER $

CREATE PROCEDURE CONTA()
BEGIN 
    SELECT 10 + 10 AS CONTA;
END
$

DELIMITER ;

CALL CONTA();

DROP PROCEDURE CONTA;

DELIMITER $

CREATE PROCEDURE CONTA(NUMERO1 INT, NUMERO2 INT)
BEGIN 
    SELECT NUMERO1 + NUMERO2 AS CONTA;
END
$

DELIMITER ;

CALL CONTA(100,50);
CALL CONTA(564,45);
CALL CONTA(54,987);
CALL CONTA(255,12);

/* TRABALHANDO COM PRODUCERES EM TABLES */

CREATE DATABASE PROJETO;

USE PROJETO;

CREATE TABLE CURSOS(
    IDCURSO INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(30) NOT NULL,
    HORAS INT(3) NOT NULL,
    VALOR FLOAT(10,2) NOT NULL
);

SHOW TABLES;

INSERT INTO CURSOS VALUES (NULL, 'JAVA',30, 500.00);
INSERT INTO CURSOS VALUES (NULL, 'FUNDAMENTOS DE BANCO DE DADOS',40, 700.00);

SELECT * FROM CURSOS;

DELIMITER #

STATUS

CREATE PROCEDURE CAD_CURSO(P_NOME VARCHAR(30),
                 P_HORAS INT(3),
                 P_PRECO FLOAT(10,2))
BEGIN
    INSERT INTO CURSOS VALUES(NULL, P_NOME, P_HORAS, P_PRECO);
END
#

DELIMITER ;

CALL CAD_CURSO('BI SQL SERVER', 35, 3000.00);
CALL CAD_CURSO('POWER BI', 20, 1000.00);
CALL CAD_CURSO('TABLAO', 1000, 1200.00);

/* CRIAR UMA PROCEDURE PARA CONSULTAR CURSOS */

DELIMITER #

CREATE PROCEDURE CONSULT_CURSOS(P_NOME VARCHAR(30),
                                P_HORAS INT(3),
                                P_PRECO FLOAT(10,2))
BEGIN
    INSERT INTO CURSOS VALUES(NULL, P_NOME, P_HORAS, P_PRECO);
END
#

CALL CONSULT_CURSOS('SQL SERVER', 35, 200.00);