SELECT COUNT(*) FROM FUNCIONARIOS;

/* COMO ESTAMOS TRABALHANDO COM OR E A SEGUNDA CONDICAO É OPCIONAL COLOCAMOS NA PRIMEIRA CONDIÇÃO QUEM TEM MAIS CHANCE DE UMA SAIDA VERDADEIRA, POIS A SEGUNDA CONDIÇÃO NÃO SERA CHECADA NESSE CASO */
SELECT * FROM FUNCIONARIOS
WHERE DEPARTAMENTO = 'ROUPAS'
OR 
DEPARTAMENTO = 'FILMES';

SELECT COUNT(*), DEPARTAMENTO 
FROM FUNCIONARIOS
GROUP BY  DEPARTAMENTO;

SELECT COUNT(*), DEPARTAMENTO 
FROM FUNCIONARIOS
GROUP BY  DEPARTAMENTO
ORDER BY 1;

WHERE DEPARTAMENTO = 'Filmes' OR DEPARTAMENTO = 'Roupas';

SELECT COUNT(*), SEXO
FROM FUNCIONARIOS
GROUP BY SEXO;

SELECT COUNT(*), DEPARTAMENTO
FROM FUNCIONARIOS
GROUP BY DEPARTAMENTO;

SELECT * FROM FUNCIONARIOS
WHERE 
( DEPARTAMENTO = 'LAR' AND SEXO = 'FEMININO')
OR
( DEPARTAMENTO = 'FILMES' AND SEXO = 'FEMININO');

SELECT * FROM FUNCIONARIOS
WHERE
SEXO = 'MARCULINO' OR
DEPARTAMENTO = 'JARDIM';