/* OPERADORES LÓGICOS 
    OR -> PARA QUE A SAIDA DA QUERY SEJA VERDADEIRA, BASTA QUE APENAS UMA CONDIÇÃO SEJA VERDADEIRA!
    AND -> PARA QUE A SAIDA SEJA VERDADEIRA TODAS AS CONDIÇÕES PRECISAM SER VERDADEIRA!
*/

SELECT NOME_DO_AUTOR, SEXO_DO_AUTOR, UF_DA_EDITORA
FROM LIVROS
WHERE 
SEXO_DO_AUTOR = 'MASCULINO' AND (UF_DA_EDITORA = 'SP' OR UF_DA_EDITORA = 'RJ');

/* OR - OU */

SELECT * FROM CLIENTE;

SELECT NOME, SEXO, ENDERECO FROM CLIENTE
WHERE
SEXO = 'M' OR ENDERECO LIKE '%SC';

SELECT NOME, SEXO, ENDERECO FROM CLIENTE
WHERE
SEXO = 'M' AND ENDERECO LIKE '%SC';

SELECT NOME, SEXO, ENDERECO FROM CLIENTE
WHERE 
SEXO = 'F' OR ENDERECO LIKE '%PENHA';

/* AND - E */

SELECT NOME, SEXO, ENDERECO FROM CLIENTE
WHERE 
SEXO = 'M' AND ENDERECO LIKE '%SC';

SELECT NOME, SEXO, ENDERECO FROM CLIENTE
WHERE
SEXO = 'F' AND ENDERECO LIKE '%PENHA';

/* COUNT(*), GROUP BY, PERFORMANCE COM OPERADORES LÓGICOS */
/* CONTANDO OS REGISTROS DE UMA TABELA*/

SELECT COUNT(*) AS 'Quantidade de registro da tabela Cliente'
FROM CLIENTE;

/* OPERADORES GROUP BY */

SELECT SEXO, COUNT(*)
FROM CLIENTE;

SELECT SEXO, COUNT(*)
FROM CLIENTE
GROUP BY SEXO;

/* PERFORMANCE EM OPERADORES LÓGICOS */

/* 1 MILHÃO DE REGISTROS

PARA CONTAR
SELECT COUNT (*) FROM CLIENTE;

SELECT SEXO, COUNT(*) FROM CLIENTE;

SELECT SEXO, COUNT(*) FROM CLIENTE
GROUP BY SEXO;

SELECT CIDADE, COUNT(*) FROM CLIENTE
GROUP BY CIDADE;

CONDICAO 
SEXO = F
CIDADE = PENHA

SITUAÇÃO - TRATANDO COM OU / OR
70% MULHERES = SEXO = F
30% MORA EM PENHA

SELECT NOME, SEXO, ENDERECO
FROM CLIENTE
WHERE SEXO = 'F'
OR CIDADE = 'PENHA';

SITUAÇÃO - TRATANDO COM E / AND
70% MULHERES = SEXO = F
30% MORA EM PENHA

SELECT NOME, SEXO, ENDERECO
FROM CLIENTE
WHERE CIDADE = 'PENHA'
AND SEXO = 'F';